#ifndef _RESULT_DEFINE_H__
#define _RESULT_DEFINE_H__


enum LOGIN_RESULT
{
	LOGINR_SUCCESS,				//成功
	LOGINR_AUTH_FAIL,			//验证失败
	LOGINR_VERSION_FAIL,		//版本错误
	LOGINR_STOP_SERVICE,		//暂时停止服务
};

enum CONNECT_RESULT
{
	CONNECT_SUCCESS,
	CONNECT_AUTH_FAIL,
	CONNECT_STOP_SERVICE,
};
#endif
